### PR TITLE
Rename run_aviary

### PR DESCRIPTION
**Pull request by xjjiang**
### Summary

Rename `run_aviary` to `setup_and_run_aviary` because that is what it does.

Note: it will cause backward incompatibility. Should we make this change?

### Related Issues

- Resolves #

### Backwards incompatibilities

updating the api will cause backwards incompatibility for any users currently importing run_aviary from the api

### New Dependencies

None

### CODE REVIEW

**Comment by crecine** [comment]
This might be a good opportunity to add a deprecation warning to the API, and support both for now.

**Comment by xjjiang** [comment]
> This might be a good opportunity to add a deprecation warning to the API, and support both for now.

It would be a good practice for the future. Any guideline? @crecine @Kenneth-T-Moore

**Comment by crecine** [comment]
@Kenneth-T-Moore 
I tried adding a deprecation warning, but running `examples/run_basic_aviary_example.py` doesn't actually produce a warning.
https://github.com/xjjiang/om-Aviary/pull/1/files

**Comment by johnjasa** [comment]
I'm not certain if this change is a helpful one for users and I want to discuss it here.

Although the `run_aviary` command does indeed setup and run the model, I think the name `setup_and_run_aviary` is clunky, especially for low-level uses of Aviary. I think `run_aviary` is much more memorable and clear.

@xjjiang could you tell me more about the benefits of renaming here? I welcome input from others too!

**Comment by Kenneth-T-Moore** [comment]
@crecine  
I am not sure what is swallowing that warning. I would have to play around.

@johnjasa 
I am not sure we need this change either. I think the level 1 user should stay unaware of the setup/run distinction until they have learned the basics.

**Comment by crecine** [comment]
I believe this was intended to reduce some confusion regarding the difference between `run_aviary` and `run_aviary_problem`.
Are we expecting level 1 users to be importing from the api? I would think that this would have the biggest effect on level 2 users that want to script/automate running Aviary

**Comment by xjjiang** [comment]
I just thought `setup_and_run_aviary` is what this function actually does. It is okay if we keep as it is.

**Comment by xjjiang** [comment]
I will withdraw this PR in one hour if you are not appose it.

**Pull request closed without merging**
